inherit_gem:
  fablicop:
    - 'config/.base_rubocop.yml'

AllCops:
  Exclude:
    - 'src/bundle/**/*'
    - 'node_modules/**/*'
    - 'rubies/**/*'
    - 'npm/node_modules'
    - 'gem/pkg'

RSpec/InstanceVariable:
  Enabled: false

Rails/Output:
  AutoCorrect: false

Metrics/AbcSize:
  Max: 24

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Pluck:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Rails/NegateInclude:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/GuardClause:
  Enabled: false
